module ImportStatus
  NOT_STARTED = 'NOT_STARTED'
  IN_PROGRESS = 'IN_PROGRESS'
  ERROR = 'ERROR'
  COMPLETED = 'COMPLETED'
  MANAGER_ASSIGNMENT_PENDING = 'MANAGER_ASSIGNMENT_PENDING'
  COMPLETED_WITH_ERRORS = 'COMPLETED_WITH_ERRORS'
end